# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\axesMPL.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 1066)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 410, 701, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = MplWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 350, 701, 41))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.but_filter_data = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.but_filter_data.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_filter_data.sizePolicy().hasHeightForWidth())
        self.but_filter_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_filter_data.setFont(font)
        self.but_filter_data.setObjectName("but_filter_data")
        self.gridLayout_2.addWidget(self.but_filter_data, 0, 2, 1, 1)
        self.but_calc_ib = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.but_calc_ib.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_calc_ib.sizePolicy().hasHeightForWidth())
        self.but_calc_ib.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_calc_ib.setFont(font)
        self.but_calc_ib.setObjectName("but_calc_ib")
        self.gridLayout_2.addWidget(self.but_calc_ib, 0, 1, 1, 1)
        self.but_init_data = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.but_init_data.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_init_data.sizePolicy().hasHeightForWidth())
        self.but_init_data.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_init_data.setFont(font)
        self.but_init_data.setObjectName("but_init_data")
        self.gridLayout_2.addWidget(self.but_init_data, 0, 0, 1, 1)
        self.but_create_cnc = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.but_create_cnc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_create_cnc.sizePolicy().hasHeightForWidth())
        self.but_create_cnc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_create_cnc.setFont(font)
        self.but_create_cnc.setObjectName("but_create_cnc")
        self.gridLayout_2.addWidget(self.but_create_cnc, 0, 3, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 210, 241))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.par_il = QtWidgets.QLineEdit(self.groupBox)
        self.par_il.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_il.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_il.setObjectName("par_il")
        self.gridLayout_4.addWidget(self.par_il, 3, 1, 1, 1)
        self.par_t_soll = QtWidgets.QLineEdit(self.groupBox)
        self.par_t_soll.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_t_soll.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_t_soll.setObjectName("par_t_soll")
        self.gridLayout_4.addWidget(self.par_t_soll, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1, QtCore.Qt.AlignRight)
        self.par_i0 = QtWidgets.QLineEdit(self.groupBox)
        self.par_i0.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_i0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_i0.setObjectName("par_i0")
        self.gridLayout_4.addWidget(self.par_i0, 1, 1, 1, 1)
        self.par_d_ang = QtWidgets.QLineEdit(self.groupBox)
        self.par_d_ang.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_d_ang.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_d_ang.setObjectName("par_d_ang")
        self.gridLayout_4.addWidget(self.par_d_ang, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_25 = QtWidgets.QLabel(self.groupBox)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 5, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 4, 0, 1, 1, QtCore.Qt.AlignRight)
        self.par_di = QtWidgets.QLineEdit(self.groupBox)
        self.par_di.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_di.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_di.setObjectName("par_di")
        self.gridLayout_4.addWidget(self.par_di, 2, 1, 1, 1)
        self.par_ang = QtWidgets.QLineEdit(self.groupBox)
        self.par_ang.setMaximumSize(QtCore.QSize(38, 16777215))
        self.par_ang.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_ang.setObjectName("par_ang")
        self.gridLayout_4.addWidget(self.par_ang, 4, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 4, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 260, 211, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.filt_met_sav = QtWidgets.QRadioButton(self.groupBox_2)
        self.filt_met_sav.setChecked(True)
        self.filt_met_sav.setObjectName("filt_met_sav")
        self.gridLayout.addWidget(self.filt_met_sav, 0, 0, 1, 1)
        self.par_n_sav = QtWidgets.QLineEdit(self.groupBox_2)
        self.par_n_sav.setMaximumSize(QtCore.QSize(30, 16777210))
        self.par_n_sav.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.par_n_sav.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_n_sav.setObjectName("par_n_sav")
        self.gridLayout.addWidget(self.par_n_sav, 0, 2, 1, 1)
        self.label_P_sav = QtWidgets.QLabel(self.groupBox_2)
        self.label_P_sav.setObjectName("label_P_sav")
        self.gridLayout.addWidget(self.label_P_sav, 0, 3, 1, 1, QtCore.Qt.AlignRight)
        self.filt_met_med = QtWidgets.QRadioButton(self.groupBox_2)
        self.filt_met_med.setObjectName("filt_met_med")
        self.gridLayout.addWidget(self.filt_met_med, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.par_p_sav = QtWidgets.QLineEdit(self.groupBox_2)
        self.par_p_sav.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_p_sav.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_p_sav.setObjectName("par_p_sav")
        self.gridLayout.addWidget(self.par_p_sav, 0, 4, 1, 1)
        self.txt_n_med = QtWidgets.QLabel(self.groupBox_2)
        self.txt_n_med.setObjectName("txt_n_med")
        self.gridLayout.addWidget(self.txt_n_med, 1, 1, 1, 1, QtCore.Qt.AlignRight)
        self.par_n_med = QtWidgets.QLineEdit(self.groupBox_2)
        self.par_n_med.setEnabled(False)
        self.par_n_med.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_n_med.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_n_med.setObjectName("par_n_med")
        self.gridLayout.addWidget(self.par_n_med, 1, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 100, 211, 241))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.par_slp_out_1_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_1_1.setMaximumSize(QtCore.QSize(29, 16777215))
        self.par_slp_out_1_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_1_1.setObjectName("par_slp_out_1_1")
        self.gridLayout_3.addWidget(self.par_slp_out_1_1, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 1, 4, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 3, 4, 1, 1)
        self.par_slp_out_1_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_1_3.setMaximumSize(QtCore.QSize(29, 16777215))
        self.par_slp_out_1_3.setText("")
        self.par_slp_out_1_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_1_3.setObjectName("par_slp_out_1_3")
        self.gridLayout_3.addWidget(self.par_slp_out_1_3, 3, 3, 1, 1)
        self.par_slp_out_1_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_1_2.setMaximumSize(QtCore.QSize(29, 16777215))
        self.par_slp_out_1_2.setText("")
        self.par_slp_out_1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_1_2.setObjectName("par_slp_out_1_2")
        self.gridLayout_3.addWidget(self.par_slp_out_1_2, 2, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 2, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setMaximumSize(QtCore.QSize(38, 16777215))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setMaximumSize(QtCore.QSize(23, 16777215))
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 2, 1, 1)
        self.par_slp_out_0_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_0_2.setMaximumSize(QtCore.QSize(34, 16777215))
        self.par_slp_out_0_2.setText("")
        self.par_slp_out_0_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_0_2.setObjectName("par_slp_out_0_2")
        self.gridLayout_3.addWidget(self.par_slp_out_0_2, 2, 1, 1, 1)
        self.par_slp_in = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_in.setMaximumSize(QtCore.QSize(34, 16777215))
        self.par_slp_in.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_in.setObjectName("par_slp_in")
        self.gridLayout_3.addWidget(self.par_slp_in, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setMaximumSize(QtCore.QSize(38, 16777215))
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.par_slp_out_0_3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_0_3.setMaximumSize(QtCore.QSize(34, 16777215))
        self.par_slp_out_0_3.setText("")
        self.par_slp_out_0_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_0_3.setObjectName("par_slp_out_0_3")
        self.gridLayout_3.addWidget(self.par_slp_out_0_3, 3, 1, 1, 1)
        self.par_slp_out_0_1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_0_1.setMaximumSize(QtCore.QSize(34, 16777215))
        self.par_slp_out_0_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_0_1.setObjectName("par_slp_out_0_1")
        self.gridLayout_3.addWidget(self.par_slp_out_0_1, 1, 1, 1, 1)
        self.par_slp_out_foc = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_foc.setMaximumSize(QtCore.QSize(34, 16777215))
        self.par_slp_out_foc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_foc.setObjectName("par_slp_out_foc")
        self.gridLayout_3.addWidget(self.par_slp_out_foc, 5, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_27 = QtWidgets.QLabel(self.groupBox_3)
        self.label_27.setMaximumSize(QtCore.QSize(23, 16777215))
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 5, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMaximumSize(QtCore.QSize(38, 16777215))
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 5, 0, 1, 1, QtCore.Qt.AlignRight)
        self.par_slp_out_vs = QtWidgets.QLineEdit(self.groupBox_3)
        self.par_slp_out_vs.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_slp_out_vs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_slp_out_vs.setObjectName("par_slp_out_vs")
        self.gridLayout_3.addWidget(self.par_slp_out_vs, 4, 1, 1, 1, QtCore.Qt.AlignRight)
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 4, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.groupBox_3)
        self.label_39.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 2, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox_3)
        self.label_40.setMaximumSize(QtCore.QSize(33, 16777215))
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 3, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 0, 481, 88))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.txt_path = QtWidgets.QLineEdit(self.layoutWidget)
        self.txt_path.setText("")
        self.txt_path.setObjectName("txt_path")
        self.gridLayout_7.addWidget(self.txt_path, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 1, 0, 1, 1)
        self.txt_versuch = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_versuch.sizePolicy().hasHeightForWidth())
        self.txt_versuch.setSizePolicy(sizePolicy)
        self.txt_versuch.setObjectName("txt_versuch")
        self.gridLayout_7.addWidget(self.txt_versuch, 2, 1, 1, 1)
        self.txt_file = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_file.sizePolicy().hasHeightForWidth())
        self.txt_file.setSizePolicy(sizePolicy)
        self.txt_file.setObjectName("txt_file")
        self.gridLayout_7.addWidget(self.txt_file, 1, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_7.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 0, 1, 1)
        self.but_open_file = QtWidgets.QToolButton(self.layoutWidget)
        self.but_open_file.setObjectName("but_open_file")
        self.gridLayout_7.addWidget(self.but_open_file, 0, 2, 1, 1)
        self.but_replot_data = QtWidgets.QPushButton(self.centralwidget)
        self.but_replot_data.setEnabled(False)
        self.but_replot_data.setGeometry(QtCore.QRect(600, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.but_replot_data.setFont(font)
        self.but_replot_data.setObjectName("but_replot_data")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 930, 701, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.but_save_data = QtWidgets.QPushButton(self.groupBox_4)
        self.but_save_data.setEnabled(False)
        self.but_save_data.setGeometry(QtCore.QRect(590, 20, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_save_data.setFont(font)
        self.but_save_data.setObjectName("but_save_data")
        self.cb_save_cnc = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_save_cnc.setGeometry(QtCore.QRect(10, 20, 51, 17))
        self.cb_save_cnc.setChecked(True)
        self.cb_save_cnc.setObjectName("cb_save_cnc")
        self.cb_save_csv = QtWidgets.QCheckBox(self.groupBox_4)
        self.cb_save_csv.setGeometry(QtCore.QRect(10, 50, 51, 17))
        self.cb_save_csv.setChecked(True)
        self.cb_save_csv.setObjectName("cb_save_csv")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 30, 471, 26))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_34 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_5.addWidget(self.label_34)
        self.txt_outfolder = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.txt_outfolder.setObjectName("txt_outfolder")
        self.horizontalLayout_5.addWidget(self.txt_outfolder)
        self.but_out = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        self.but_out.setObjectName("but_out")
        self.horizontalLayout_5.addWidget(self.but_out)
        self.but_QuickPlot = QtWidgets.QPushButton(self.centralwidget)
        self.but_QuickPlot.setEnabled(False)
        self.but_QuickPlot.setGeometry(QtCore.QRect(600, 10, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_QuickPlot.setFont(font)
        self.but_QuickPlot.setObjectName("but_QuickPlot")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(450, 100, 261, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setContentsMargins(-1, 3, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.par_l_ns = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_l_ns.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_l_ns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_l_ns.setObjectName("par_l_ns")
        self.gridLayout_5.addWidget(self.par_l_ns, 2, 3, 1, 1)
        self.par_vs = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_vs.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_vs.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_vs.setObjectName("par_vs")
        self.gridLayout_5.addWidget(self.par_vs, 0, 1, 1, 1)
        self.par_vs_gk = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_vs_gk.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_vs_gk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_vs_gk.setObjectName("par_vs_gk")
        self.gridLayout_5.addWidget(self.par_vs_gk, 1, 1, 1, 1)
        self.par_l_gk = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_l_gk.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_l_gk.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_l_gk.setObjectName("par_l_gk")
        self.gridLayout_5.addWidget(self.par_l_gk, 1, 3, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 1, 4, 1, 1)
        self.par_vs_ns = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_vs_ns.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_vs_ns.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_vs_ns.setObjectName("par_vs_ns")
        self.gridLayout_5.addWidget(self.par_vs_ns, 2, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 4, 1, 1)
        self.rb_vs_step = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_vs_step.setChecked(True)
        self.rb_vs_step.setObjectName("rb_vs_step")
        self.gridLayout_5.addWidget(self.rb_vs_step, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 2, 2, 1, 1)
        self.rb_vs_const = QtWidgets.QRadioButton(self.groupBox_5)
        self.rb_vs_const.setChecked(False)
        self.rb_vs_const.setObjectName("rb_vs_const")
        self.gridLayout_5.addWidget(self.rb_vs_const, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 1, 2, 1, 1)
        self.par_vs_trans = QtWidgets.QLineEdit(self.groupBox_5)
        self.par_vs_trans.setMaximumSize(QtCore.QSize(30, 16777215))
        self.par_vs_trans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.par_vs_trans.setObjectName("par_vs_trans")
        self.gridLayout_5.addWidget(self.par_vs_trans, 3, 3, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 3, 4, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 3, 2, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.but_trim_csv = QtWidgets.QPushButton(self.centralwidget)
        self.but_trim_csv.setEnabled(False)
        self.but_trim_csv.setGeometry(QtCore.QRect(510, 10, 81, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.but_trim_csv.sizePolicy().hasHeightForWidth())
        self.but_trim_csv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.but_trim_csv.setFont(font)
        self.but_trim_csv.setObjectName("but_trim_csv")
        self.layoutWidget.raise_()
        self.verticalLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.groupBox_3.raise_()
        self.but_replot_data.raise_()
        self.groupBox_4.raise_()
        self.but_QuickPlot.raise_()
        self.groupBox_5.raise_()
        self.but_trim_csv.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionOpen_File)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.txt_path, self.but_open_file)
        MainWindow.setTabOrder(self.but_open_file, self.txt_file)
        MainWindow.setTabOrder(self.txt_file, self.txt_versuch)
        MainWindow.setTabOrder(self.txt_versuch, self.but_trim_csv)
        MainWindow.setTabOrder(self.but_trim_csv, self.but_QuickPlot)
        MainWindow.setTabOrder(self.but_QuickPlot, self.but_replot_data)
        MainWindow.setTabOrder(self.but_replot_data, self.but_init_data)
        MainWindow.setTabOrder(self.but_init_data, self.but_calc_ib)
        MainWindow.setTabOrder(self.but_calc_ib, self.but_filter_data)
        MainWindow.setTabOrder(self.but_filter_data, self.but_create_cnc)
        MainWindow.setTabOrder(self.but_create_cnc, self.par_t_soll)
        MainWindow.setTabOrder(self.par_t_soll, self.par_i0)
        MainWindow.setTabOrder(self.par_i0, self.par_di)
        MainWindow.setTabOrder(self.par_di, self.par_il)
        MainWindow.setTabOrder(self.par_il, self.par_ang)
        MainWindow.setTabOrder(self.par_ang, self.par_d_ang)
        MainWindow.setTabOrder(self.par_d_ang, self.par_slp_in)
        MainWindow.setTabOrder(self.par_slp_in, self.par_slp_out_0_1)
        MainWindow.setTabOrder(self.par_slp_out_0_1, self.par_slp_out_1_1)
        MainWindow.setTabOrder(self.par_slp_out_1_1, self.par_slp_out_0_2)
        MainWindow.setTabOrder(self.par_slp_out_0_2, self.par_slp_out_1_2)
        MainWindow.setTabOrder(self.par_slp_out_1_2, self.par_slp_out_0_3)
        MainWindow.setTabOrder(self.par_slp_out_0_3, self.par_slp_out_1_3)
        MainWindow.setTabOrder(self.par_slp_out_1_3, self.par_slp_out_vs)
        MainWindow.setTabOrder(self.par_slp_out_vs, self.par_slp_out_foc)
        MainWindow.setTabOrder(self.par_slp_out_foc, self.rb_vs_const)
        MainWindow.setTabOrder(self.rb_vs_const, self.par_vs)
        MainWindow.setTabOrder(self.par_vs, self.rb_vs_step)
        MainWindow.setTabOrder(self.rb_vs_step, self.par_vs_gk)
        MainWindow.setTabOrder(self.par_vs_gk, self.par_l_gk)
        MainWindow.setTabOrder(self.par_l_gk, self.par_vs_ns)
        MainWindow.setTabOrder(self.par_vs_ns, self.par_l_ns)
        MainWindow.setTabOrder(self.par_l_ns, self.par_vs_trans)
        MainWindow.setTabOrder(self.par_vs_trans, self.filt_met_sav)
        MainWindow.setTabOrder(self.filt_met_sav, self.par_n_sav)
        MainWindow.setTabOrder(self.par_n_sav, self.par_p_sav)
        MainWindow.setTabOrder(self.par_p_sav, self.filt_met_med)
        MainWindow.setTabOrder(self.filt_met_med, self.par_n_med)
        MainWindow.setTabOrder(self.par_n_med, self.cb_save_cnc)
        MainWindow.setTabOrder(self.cb_save_cnc, self.cb_save_csv)
        MainWindow.setTabOrder(self.cb_save_csv, self.txt_outfolder)
        MainWindow.setTabOrder(self.txt_outfolder, self.but_out)
        MainWindow.setTabOrder(self.but_out, self.but_save_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plot Data and Graphs"))
        self.but_filter_data.setText(_translate("MainWindow", "FILTER DATA"))
        self.but_calc_ib.setText(_translate("MainWindow", "CALC IB"))
        self.but_init_data.setText(_translate("MainWindow", "INIT DATA"))
        self.but_create_cnc.setText(_translate("MainWindow", "CREATE CNC"))
        self.groupBox.setTitle(_translate("MainWindow", "Prozessparameter"))
        self.par_il.setText(_translate("MainWindow", "1720"))
        self.par_t_soll.setText(_translate("MainWindow", "1225"))
        self.label_8.setText(_translate("MainWindow", "Linsenstrom"))
        self.par_i0.setText(_translate("MainWindow", "30"))
        self.par_d_ang.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "°C"))
        self.label_9.setText(_translate("MainWindow", "mA"))
        self.label_5.setText(_translate("MainWindow", "mA"))
        self.label_3.setText(_translate("MainWindow", "Grundstrahlstrom"))
        self.label_25.setText(_translate("MainWindow", "°"))
        self.label_6.setText(_translate("MainWindow", "mA"))
        self.label.setText(_translate("MainWindow", "Solltemperatur"))
        self.label_7.setText(_translate("MainWindow", "Strahlstromoffset"))
        self.label_24.setText(_translate("MainWindow", "Winkelinkrement"))
        self.label_22.setText(_translate("MainWindow", "Gesamtwinkel"))
        self.par_di.setText(_translate("MainWindow", "45"))
        self.par_ang.setText(_translate("MainWindow", "391"))
        self.label_23.setText(_translate("MainWindow", "°"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filterparameter"))
        self.filt_met_sav.setText(_translate("MainWindow", "Savgol"))
        self.par_n_sav.setToolTip(_translate("MainWindow", "<html><head/><body><p>Anzahl der Punkte, über die gefiltert wird. </p><p><span style=\" color:#ff0000;\">Nur </span><span style=\" font-weight:600; color:#ff0000;\">UNGERADE </span><span style=\" color:#ff0000;\">Zahlen möglich!</span></p></body></html>"))
        self.par_n_sav.setText(_translate("MainWindow", "99"))
        self.label_P_sav.setText(_translate("MainWindow", "P"))
        self.filt_met_med.setText(_translate("MainWindow", "Median"))
        self.label_4.setText(_translate("MainWindow", "n"))
        self.par_p_sav.setToolTip(_translate("MainWindow", "Polynom n-ten Grades, welches zur Annäherung genutzt wird."))
        self.par_p_sav.setText(_translate("MainWindow", "5"))
        self.txt_n_med.setText(_translate("MainWindow", "n"))
        self.par_n_med.setText(_translate("MainWindow", "5"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Slope-Parameter"))
        self.par_slp_out_1_1.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "%"))
        self.label_21.setText(_translate("MainWindow", "%"))
        self.label_18.setText(_translate("MainWindow", "° auf"))
        self.label_20.setText(_translate("MainWindow", "%"))
        self.label_12.setText(_translate("MainWindow", "IN"))
        self.label_13.setText(_translate("MainWindow", "°"))
        self.par_slp_in.setText(_translate("MainWindow", "20"))
        self.label_15.setText(_translate("MainWindow", "OUT"))
        self.par_slp_out_0_1.setText(_translate("MainWindow", "2"))
        self.par_slp_out_foc.setText(_translate("MainWindow", "300"))
        self.label_27.setText(_translate("MainWindow", "mA"))
        self.label_33.setText(_translate("MainWindow", "IL-Off"))
        self.par_slp_out_vs.setText(_translate("MainWindow", "25"))
        self.label_35.setText(_translate("MainWindow", "mm/s"))
        self.label_39.setText(_translate("MainWindow", "° auf"))
        self.label_40.setText(_translate("MainWindow", "° auf"))
        self.label_37.setText(_translate("MainWindow", "Dateiname"))
        self.label_36.setText(_translate("MainWindow", "Dateipfad"))
        self.label_38.setText(_translate("MainWindow", "Versuch"))
        self.but_open_file.setText(_translate("MainWindow", "..."))
        self.but_replot_data.setToolTip(_translate("MainWindow", "Berechnet anhand der geänderten Parameter die Daten neu. \n"
"Der Plot erfolgt in der aktuellen Zoomstufe."))
        self.but_replot_data.setText(_translate("MainWindow", "Replot"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Output"))
        self.but_save_data.setText(_translate("MainWindow", "Save Data"))
        self.cb_save_cnc.setText(_translate("MainWindow", "CNC"))
        self.cb_save_csv.setText(_translate("MainWindow", "CSV"))
        self.label_34.setText(_translate("MainWindow", "Ausgabeordner"))
        self.but_out.setText(_translate("MainWindow", "..."))
        self.but_QuickPlot.setToolTip(_translate("MainWindow", "Lässt automatisch alle Berechnungen ablaufen und plottet die Daten.\n"
"(sinnvoll für erste Darstellung der Messwerte)"))
        self.but_QuickPlot.setText(_translate("MainWindow", "Init Plot"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Vorschub"))
        self.par_l_ns.setToolTip(_translate("MainWindow", "<html><head/><body><p>Bereich der Nockenhubkontur</p></body></html>"))
        self.par_l_ns.setText(_translate("MainWindow", "160"))
        self.par_vs.setText(_translate("MainWindow", "20"))
        self.par_vs_gk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Geschwindigkeit für Grundkreis</p></body></html>"))
        self.par_vs_gk.setText(_translate("MainWindow", "25"))
        self.par_l_gk.setToolTip(_translate("MainWindow", "<html><head/><body><p>Entfernung auf Grundkreis OHNE SLope</p></body></html>"))
        self.par_l_gk.setText(_translate("MainWindow", "86"))
        self.label_26.setText(_translate("MainWindow", "°"))
        self.par_vs_ns.setToolTip(_translate("MainWindow", "<html><head/><body><p>Geschwindigkeit für Nockenspitze</p></body></html>"))
        self.par_vs_ns.setText(_translate("MainWindow", "20"))
        self.label_30.setText(_translate("MainWindow", "°"))
        self.rb_vs_step.setText(_translate("MainWindow", "gestuft"))
        self.label_28.setText(_translate("MainWindow", "mm/s"))
        self.label_29.setText(_translate("MainWindow", "mm/s für"))
        self.rb_vs_const.setText(_translate("MainWindow", "konstant"))
        self.label_14.setText(_translate("MainWindow", "mm/s für"))
        self.par_vs_trans.setToolTip(_translate("MainWindow", "<html><head/><body><p>Über wie viel Grad wurde die Vorschubgeschwindigkeit interpoliert?</p></body></html>"))
        self.par_vs_trans.setText(_translate("MainWindow", "5"))
        self.label_31.setText(_translate("MainWindow", "°"))
        self.label_32.setText(_translate("MainWindow", "Übergang"))
        self.but_trim_csv.setToolTip(_translate("MainWindow", "Punkte in der CSV durch Kommas ersetzen."))
        self.but_trim_csv.setText(_translate("MainWindow", "TRIM\n"
"CSV"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))
        self.actionOpen_File.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+D"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
